"""MCP Mommy: local web dashboard + tray icon to start/stop/monitor the MCP
servers and the Discord bot in this project.

SECURITY: binds to 127.0.0.1 only and has no authentication. It gives control over
starting/stopping/restarting local subprocesses -- do not expose it on a network
interface, do not add port forwarding, and do not run it on a shared machine.
"""
import atexit
import os
import subprocess
import sys
import threading
import time
import webbrowser
from collections import deque

from flask import Flask, jsonify, send_file
from PIL import Image, ImageDraw
import pystray

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

_venv_python = os.path.join(PROJECT_ROOT, ".venv", "Scripts", "python.exe")
PYTHON = _venv_python if os.path.exists(_venv_python) else sys.executable

SERVERS = {
    "ubc-mcp": os.path.join(PROJECT_ROOT, "mcp_server.py"),
    "google-tasks-mcp": os.path.join(PROJECT_ROOT, "google_tasks_mcp.py"),
    "gmail-mcp": os.path.join(PROJECT_ROOT, "gmail_mcp.py"),
    "discord-bot": os.path.join(PROJECT_ROOT, "discord_bot.py"),
}

LOG_LINES = 200

# Plain-text brief regenerated by the scheduled Claude task; rendered at the
# bottom of the dashboard. Missing file is fine -- the panel just says so.
BRIEF_PATH = os.path.join(PROJECT_ROOT, "src", "context", "ubc-brief.txt")
FAVICON_PATH = os.path.join(PROJECT_ROOT, "src", "assets", "profile.ico")

# Tracks the PID we last spawned for each managed server, on disk, so that if a
# previous MCP Mommy process dies uncleanly (crash, force-killed, etc. -- skipping
# stop()/atexit) we can find and clean up the orphan before starting a fresh one,
# instead of duplicate instances piling up (e.g. the Discord bot replying twice).
PIDS_DIR = os.path.join(PROJECT_ROOT, ".mcp_mommy_pids")
os.makedirs(PIDS_DIR, exist_ok=True)


class ManagedServer:
    def __init__(self, name, script_path):
        self.name = name
        self.script_path = script_path
        self.process = None
        self.logs = deque(maxlen=LOG_LINES)
        self.started_at = None
        self.pid_file = os.path.join(PIDS_DIR, f"{name}.pid")

    def _kill_tree(self, pid):
        # /T kills the whole process tree, not just this pid -- some launches on
        # this system leave a surviving child that plain terminate()/kill() miss.
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(pid)],
            capture_output=True,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )

    def _kill_stale_orphan(self):
        """If a previous MCP Mommy run left this exact child still alive (its own
        parent already exited), clean it up before starting a new one. Only ever
        acts on a PID we ourselves wrote to the pid file, and only after confirming
        that PID's command line still matches this script -- never touches anything
        else on the system (e.g. Claude Desktop's own independent instances)."""
        if not os.path.exists(self.pid_file):
            return
        try:
            with open(self.pid_file) as f:
                old_pid = int(f.read().strip())
            result = subprocess.run(
                ["powershell", "-NoProfile", "-Command",
                 f"(Get-CimInstance Win32_Process -Filter 'ProcessId={old_pid}').CommandLine"],
                capture_output=True, text=True, timeout=5,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            )
            if os.path.basename(self.script_path) in (result.stdout or ""):
                self._kill_tree(old_pid)
        except Exception:
            pass
        finally:
            try:
                os.remove(self.pid_file)
            except OSError:
                pass

    def start(self):
        if self.is_running():
            return
        self._kill_stale_orphan()
        self.process = subprocess.Popen(
            [PYTHON, self.script_path],
            cwd=PROJECT_ROOT,
            # stdio-transport MCP servers read from stdin; DEVNULL looks like an
            # immediately-closed client and makes them exit right away, so keep
            # stdin open (as a pipe we simply never write to) instead.
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            # a console-subsystem child spawned from a windowless (pythonw) parent
            # would otherwise pop up its own blank terminal window on Windows
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
        with open(self.pid_file, "w") as f:
            f.write(str(self.process.pid))
        self.started_at = time.time()
        threading.Thread(target=self._read_logs, daemon=True).start()

    def _read_logs(self):
        proc = self.process
        if not proc or not proc.stdout:
            return
        for line in proc.stdout:
            self.logs.append(line.rstrip())

    def stop(self):
        if self.process and self.process.poll() is None:
            self._kill_tree(self.process.pid)
            try:
                self.process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                pass
        self.process = None
        self.started_at = None
        try:
            os.remove(self.pid_file)
        except OSError:
            pass

    def is_running(self):
        return self.process is not None and self.process.poll() is None

    def status(self):
        return {
            "name": self.name,
            "running": self.is_running(),
            "pid": self.process.pid if self.is_running() else None,
            "uptime": int(time.time() - self.started_at) if self.is_running() and self.started_at else 0,
            "logs": list(self.logs)[-50:],
        }


managed = {name: ManagedServer(name, path) for name, path in SERVERS.items()}


@atexit.register
def _stop_all():
    for srv in managed.values():
        srv.stop()


app = Flask(__name__)

INDEX_HTML = r"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>mcp-mommy</title>
<link rel="icon" href="/favicon.ico">
<style>
  :root {
    --bg: #0c0c0c;
    --fg: #d9d6cf;
    --dim: #6f6b64;
    --accent: #da7756;
    --ok: #7ec699;
    --bad: #e0685c;
    --rule: #3a3a3a;
  }
  * { box-sizing: border-box; }
  html, body {
    height: 100%;
    margin: 0;
    overflow-y: auto;
    overflow-x: hidden;
    scrollbar-width: none;      /* Firefox */
    -ms-overflow-style: none;   /* old Edge/IE */
  }
  html::-webkit-scrollbar, body::-webkit-scrollbar { display: none; } /* Chrome/Safari */
  body {
    font-family: ui-monospace, Consolas, monospace;
    background: var(--bg);
    color: var(--fg);
    font-size: 14px;
  }
  .page {
    display: flex;
    flex-direction: column;
    min-height: 100%;
    padding: 1.5rem 2rem;
  }
  .title-row { display: flex; align-items: center; gap: 0.7rem; margin: 0 0 1rem 0; flex: 0 0 auto; }
  .title-row img { width: 32px; height: 32px; }
  .title-row span { color: var(--accent); font-size: 1.3rem; font-weight: bold; letter-spacing: 0.12em; }
  .rule { color: var(--rule); white-space: pre; margin: 0.5rem 0; flex: 0 0 auto; }
  #servers { flex: 0 0 auto; }
  .server { padding: 0.6rem 0; border-bottom: 1px dashed var(--rule); }
  .server:last-child { border-bottom: none; }
  .row { display: flex; align-items: baseline; gap: 0.75rem; flex-wrap: wrap; }
  .name { color: var(--fg); font-weight: bold; min-width: 18ch; }
  .tag.running { color: var(--ok); }
  .tag.stopped { color: var(--bad); }
  .meta { color: var(--dim); margin: 0.5rem 0; flex: 0 0 auto; }
  .cmds a { color: var(--dim); text-decoration: none; cursor: pointer; margin-right: 1rem; }
  .cmds a:hover { color: var(--accent); text-decoration: underline; }
  .prompt { color: var(--accent); }
  .brief-wrap { flex: 1 1 auto; }
  pre.brief { color: var(--fg); margin: 0; white-space: pre-wrap; line-height: 1.35; }
  pre.brief .hot { color: var(--bad); }
  pre.brief .go  { color: var(--accent); font-weight: bold; }
  pre.brief .dim { color: var(--dim); }
</style>
</head>
<body>
<div class="page">
<div class="title-row"><img src="/favicon.ico" alt=""><span>MCP MOMMY</span></div>
<p class="rule">------------------------------------------------------------------------</p>
<div id="servers"></div>
<p class="rule">------------------------------------------------------------------------</p>
<p class="meta"><span class="prompt">$</span> polling every 2s, 127.0.0.1 only, no auth</p>
<p class="rule">------------------------------------------------------------------------</p>
<div class="brief-wrap"><pre class="brief" id="brief">loading brief...</pre></div>
<p class="meta"><span class="prompt">$</span> <span id="briefmeta">src/context/ubc-brief.txt</span></p>
</div>
<script>
async function act(name, action) {
  await fetch(`/api/${name}/${action}`, { method: 'POST' });
  refresh();
}

function render(data) {
  const root = document.getElementById('servers');
  root.innerHTML = '';
  for (const name in data) {
    const s = data[name];
    const div = document.createElement('div');
    div.className = 'server';
    const tag = s.running ? 'running' : 'stopped';
    const label = s.running ? `RUNNING pid=${s.pid} up=${s.uptime}s` : 'STOPPED';
    div.innerHTML = `
      <div class="row">
        <span class="name">${name}</span>
        <span class="tag ${tag}">[ ${label} ]</span>
      </div>
      <div class="row cmds">
        <a onclick="act('${name}','start')">start</a>
        <a onclick="act('${name}','stop')">stop</a>
        <a onclick="act('${name}','restart')">restart</a>
      </div>
    `;
    root.appendChild(div);
  }
}

async function refresh() {
  const res = await fetch('/api/status');
  render(await res.json());
}

async function refreshBrief() {
  try {
    const res = await fetch('/api/brief');
    const b = await res.json();
    const el = document.getElementById('brief');
    // escape first, then decorate -- file contents are never trusted as HTML
    const esc = t => t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
    const full = esc(b.text);
    const cut = full.indexOf('--- reference');
    let head = cut === -1 ? full : full.slice(0, cut);
    const tail = cut === -1 ? '' : full.slice(cut);
    head = head
      .replace(/^\[!\][^\n]*/gm, m => `<span class="hot">${m}</span>`)
      .replace(/^&gt;&gt;[^\n]*/gm, m => `<span class="go">${m}</span>`);
    el.innerHTML = head + (tail ? `<span class="dim">${tail}</span>` : '');
    document.getElementById('briefmeta').textContent =
      b.exists ? `src/context/ubc-brief.txt \u2014 ${b.age}` : 'src/context/ubc-brief.txt \u2014 not written yet';
  } catch (e) { /* leave last good render in place */ }
}

refresh();
refreshBrief();
setInterval(refresh, 2000);
setInterval(refreshBrief, 30000);
</script>
</body>
</html>
"""


@app.route("/")
def index():
    return INDEX_HTML


@app.route("/favicon.ico")
def favicon():
    if os.path.exists(FAVICON_PATH):
        return send_file(FAVICON_PATH, mimetype="image/vnd.microsoft.icon")
    return "", 404


@app.route("/api/brief")
def api_brief():
    try:
        with open(BRIEF_PATH, encoding="utf-8") as fh:
            text = fh.read()
        mins = int((time.time() - os.path.getmtime(BRIEF_PATH)) // 60)
        if mins < 1:
            age = "just now"
        elif mins < 90:
            age = f"{mins} min ago"
        else:
            age = f"{mins // 60}h ago"
        return jsonify({"exists": True, "text": text, "age": age})
    except OSError:
        return jsonify({
            "exists": False,
            "text": "(no brief yet -- the scheduled task writes this every 4 hours)",
            "age": "",
        })


@app.route("/api/status")
def api_status():
    return jsonify({name: srv.status() for name, srv in managed.items()})


@app.route("/api/<name>/start", methods=["POST"])
def api_start(name):
    if name not in managed:
        return jsonify({"error": "unknown server"}), 404
    managed[name].start()
    return jsonify(managed[name].status())


@app.route("/api/<name>/stop", methods=["POST"])
def api_stop(name):
    if name not in managed:
        return jsonify({"error": "unknown server"}), 404
    managed[name].stop()
    return jsonify(managed[name].status())


@app.route("/api/<name>/restart", methods=["POST"])
def api_restart(name):
    if name not in managed:
        return jsonify({"error": "unknown server"}), 404
    managed[name].stop()
    managed[name].start()
    return jsonify(managed[name].status())


@app.route("/api/quit", methods=["POST"])
def api_quit():
    # graceful shutdown -- stops every managed child (and cleans up their pid
    # files) before exiting, unlike force-killing this process from outside
    threading.Thread(target=lambda: (_stop_all(), os._exit(0)), daemon=True).start()
    return jsonify({"ok": True})


if __name__ == "__main__":
    for srv in managed.values():
        srv.start()
    port = int(os.getenv("MCP_MANAGER_PORT", "5055"))
    url = f"http://127.0.0.1:{port}"

    threading.Thread(
        target=lambda: app.run(host="127.0.0.1", port=port, debug=False, use_reloader=False),
        daemon=True,
    ).start()

    def _tray_icon_image():
        if os.path.exists(FAVICON_PATH):
            return Image.open(FAVICON_PATH)
        img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        draw.ellipse((2, 2, 61, 61), fill=(218, 119, 86, 255))
        draw.text((20, 18), "M", fill=(12, 12, 12, 255))
        return img

    def _on_open(icon, item):
        webbrowser.open(url)

    def _on_quit(icon, item):
        icon.stop()
        _stop_all()
        os._exit(0)

    tray = pystray.Icon(
        "mcp-mommy",
        icon=_tray_icon_image(),
        title="MCP Mommy",
        menu=pystray.Menu(
            pystray.MenuItem("Open Dashboard", _on_open, default=True),
            pystray.MenuItem("Quit", _on_quit),
        ),
    )
    tray.run()
